######################## default configuration ####################
baseURL = "https://handex.io/"
title = "Handex keydex"
theme = "saasis"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "G-9QHYLHEZGR" # example : UA-123-45

# disqus short name
disqusShortname = "themefisher-template" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # disable language from here

[[module.imports]]
  path = "github.com/hugomods/mermaid"

[params]
  [params.mermaid]
    js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'


############################# Imaging ##############################
[imaging]
quality = 100

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

[markup]
[markup.goldmark.renderer]
unsafe = true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"


######################### site variables ##############################

# page background
[params.page_background]
page_class= "" # ex: "bg-primary"
page_background_color= "#FFF" # ex: "#ff00ff", "green"
page_background_image= "" # ex: "images/bg.svg"

# customize your color and font from here.
[params.variables]
primary_color = "#FF4730"
secondary_color = "#001111"
body_color = "#fff"
text_color = "#666666"
text_color_dark = "#222222"
text_color_light = "#959595"
border_color = "#ACB9C4"
black = "#000"
white = "#fff"
light = "#fdfdfd"

# font variable
# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
primary_font = "Poppins:wght@400;500;600;700"
primary_font_type = "sans-serif" # [serif/sans-serif]
secondary_font = ""
secondary_font_type = "" # [serif/sans-serif]
icon_font = "Font Awesome 5 Free"


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"
[[params.plugins.css]]
link = "plugins/font-awesome/fontawesome.min.css"
[[params.plugins.css]]
link = "plugins/font-awesome/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/solid.css"

# JS Plugins
# [[params.plugins.js]]
# link = "plugins/jquery/jquery.min.js"
# [[params.plugins.js]]
# link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"