#################### default parameters ################################
favicon = "images/favicon32x32.png"
logo_text = "Handex.io"
logo = "images/the-handexagon-logo.png"
logo_width = "101px"
# Meta data
description = "The home of the Handex keydex"
home = "Handex"
author = "Handex"
# contact info
address = "407 W Imperial Hwy Ste H 103, Brea, CA 92821-4803"
mobile = "+17144685854"
email = "mark@handex.io"
footer_info = "We are the private company of the inventor and patent holder of Handex technology."
# form action
contact_form_action = "/create-checkout-session" # contact form works with https://formspree.io or formspree alternative
newsletter_form_action = "#" # contact form works with https://formspree.io or formspree alternative
# custom script on header
custom_script= ""

# page header background
page_header= "images/page-header.webp"

# google analytics
googleAnalytics = 'G-9QHYLHEZGR'
googleTagManager = 'GTM-ML79Q2F'

[profile]
enable = true

[login]
enable = true
link = "/login"

# Preloader
[preloader]
enable = true

# Navigation button
[navigation_button]
enable = true
label = "Preorder Now"
link = "pricing/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
# [[social]]
# title = "facebook"
# icon = "fab fa-facebook" # fontawesome icon : https://fontawesome.com/icons/
# link = "#"

# [[social]]
# title = "twitter"
# icon = "fab fa-twitter" # fontawesome icon : https://fontawesome.com/icons/
# link = "#"

# [[social]]
# title = "instagram"
# icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
# link = "#"

# [[social]]
# title = "github"
# icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
# link = "#"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.linkedin.com/company/handex-io"

