baseURL = 'http://handex.io/'
languageCode = 'en-us'
title = 'Handex keydex'
theme = 'test'
tags = ["modern"]
features = [
  "SEO Site Verification"
  ]
min_version = 0.19
email_verifier = "https://dgrl2rrg5mklw2ra7zkmumg5iu0pdwpn.lambda-url.us-east-1.on.aws"

# [[module.imports]]
#     path="github.com/jeblister/bulma"

[params] 
  logotype = "<span class=\"has-text-weight-bold\"><span class=\"has-text-danger\">Handex</span></span>"
